import type { RoleDef, RoleId } from './types';

export const ROLES: Record<RoleId, RoleDef> = {
  killer: {
    id: 'killer', name: 'Killer', team: 'evil', tier: 1, category: 'kill',
    nightAction: true, oncePerGame: false, priority: 60, minPlayers: 8, maxPlayers: 16, weight: 10,
    short: 'Kills one player every night.',
    ability: 'Each night, choose one living player. If the attack is not blocked or protected against, that player dies.',
    objective: 'Eliminate the village until Evil equals or outnumbers Good.',
    activates: 'Every night, once alive.',
    limitations: 'Cannot target the same player two nights in a row if that player survived via protection.',
    interactions: 'Blocked by Bartender roleblock. Stopped by Doctor protection or Blacksmith armor. Triggers Grandma revenge if she is the target.',
  },
  assassin: {
    id: 'assassin', name: 'Assassin', team: 'evil', tier: 3, category: 'kill',
    nightAction: true, oncePerGame: true, priority: 55, minPlayers: 12, maxPlayers: 16, weight: 6,
    short: 'A one-time forced kill that ignores protection.',
    ability: 'Once per game, choose one living player. That player dies even if protected by the Doctor or armored by the Blacksmith. This kill can still be stopped by a roleblock.',
    objective: 'Eliminate the village until Evil equals or outnumbers Good.',
    activates: 'Any single night of the Assassin\'s choosing, once alive.',
    limitations: 'The forced-kill can only be used once per game. After use, the Assassin has no night action for the rest of the game.',
    interactions: 'Ignores Doctor protection and Blacksmith armor. Still fails if the Assassin is roleblocked that night. Triggers Grandma revenge if she is the target.',
  },
  alchemist: {
    id: 'alchemist', name: 'Alchemist', team: 'evil', tier: 3, category: 'kill',
    nightAction: true, oncePerGame: false, priority: 65, minPlayers: 12, maxPlayers: 16, weight: 6,
    short: 'Poisons a player; they die the following night unless cured.',
    ability: 'Each night, choose one living player to poison. If that player is not cured before the next night begins, they die at the start of the next night, silently and without revealing a cause.',
    objective: 'Eliminate the village until Evil equals or outnumbers Good.',
    activates: 'Every night, once alive.',
    limitations: 'Only one player can be poisoned at a time; poisoning a new target does not remove poison from a previous target.',
    interactions: 'Poison deaths are separate from Killer attacks and are not stopped by Doctor protection or armor. Roleblocking the Alchemist prevents that night\'s poisoning only.',
  },
  puppeteer: {
    id: 'puppeteer', name: 'Puppeteer', team: 'evil', tier: 3, category: 'chaos',
    nightAction: true, oncePerGame: false, priority: 20, minPlayers: 13, maxPlayers: 16, weight: 5,
    short: 'Forces another player\'s night action onto a target of the Puppeteer\'s choosing.',
    ability: 'Each night, choose a living player with a night action and a target. That player\'s ability, if used, is redirected to the chosen target regardless of who they intended to act on.',
    objective: 'Eliminate the village until Evil equals or outnumbers Good.',
    activates: 'Every night, once alive.',
    limitations: 'Cannot control a roleblocked or dead player. Cannot control itself.',
    interactions: 'Resolves before other night actions (control effects apply first). Can force a Doctor to protect the wrong player, or a Killer to kill an unintended target.',
  },
  sheriff: {
    id: 'sheriff', name: 'Sheriff', team: 'good', tier: 1, category: 'info',
    nightAction: true, oncePerGame: false, priority: 80, minPlayers: 8, maxPlayers: 16, weight: 10,
    short: 'Investigates one player each night to learn their alignment.',
    ability: 'Each night, choose one living player. Privately learn whether that player is Good or Evil.',
    objective: 'Identify and eliminate every Evil player.',
    activates: 'Every night, once alive.',
    limitations: 'Learns alignment only, never the exact role.',
    interactions: 'Blocked by Bartender roleblock (result withheld). Neutral roles report their true alignment unless a card says otherwise.',
  },
  doctor: {
    id: 'doctor', name: 'Doctor', team: 'good', tier: 1, category: 'protect',
    nightAction: true, oncePerGame: false, priority: 30, minPlayers: 8, maxPlayers: 16, weight: 10,
    short: 'Protects one player from the first lethal attack each night.',
    ability: 'Each night, choose one living player. They are protected from the first lethal attack against them that night. You cannot protect the same player on two consecutive nights.',
    objective: 'Identify and eliminate every Evil player.',
    activates: 'Every night, once alive.',
    limitations: 'Cannot repeat the same target on consecutive nights. Does not stop poison or the Assassin\'s forced kill.',
    interactions: 'Stops the Killer. Triggers Grandma revenge normally if Grandma is targeted and protected (protection still applies to the attack itself).',
  },
  prophet: {
    id: 'prophet', name: 'Prophet', team: 'good', tier: 2, category: 'info',
    nightAction: true, oncePerGame: false, priority: 82, minPlayers: 9, maxPlayers: 16, weight: 8,
    short: 'Learns the exact role of one player each night.',
    ability: 'Each night, choose one living player. Privately learn their exact role.',
    objective: 'Identify and eliminate every Evil player.',
    activates: 'Every night, once alive.',
    limitations: 'Stronger than the Sheriff, so only introduced at higher player counts.',
    interactions: 'Blocked by Bartender roleblock (result withheld).',
  },
  bartender: {
    id: 'bartender', name: 'Bartender', team: 'good', tier: 2, category: 'support',
    nightAction: true, oncePerGame: false, priority: 10, minPlayers: 9, maxPlayers: 16, weight: 8,
    short: 'Distracts one player, canceling their night action.',
    ability: 'Each night, choose one living player. That player\'s night action, if any, has no effect this night.',
    objective: 'Identify and eliminate every Evil player.',
    activates: 'Every night, once alive.',
    limitations: 'Cannot block itself.',
    interactions: 'Resolves before the target\'s action. Roleblocking the Puppeteer prevents that night\'s control effect.',
  },
  blacksmith: {
    id: 'blacksmith', name: 'Blacksmith', team: 'good', tier: 2, category: 'protect',
    nightAction: true, oncePerGame: false, priority: 32, minPlayers: 10, maxPlayers: 16, weight: 7,
    short: 'Crafts armor that blocks one attack on its wearer.',
    ability: 'Every other night, choose one living player to give armor to. Armor blocks the next lethal attack against that player, then breaks.',
    objective: 'Identify and eliminate every Evil player.',
    activates: 'Every second night, once alive (cannot craft on consecutive nights).',
    limitations: 'Cannot craft on consecutive nights. Armor does not stop poison or the Assassin\'s forced kill.',
    interactions: 'Stacks independently of Doctor protection; an attack can be stopped by either.',
  },
  grandma: {
    id: 'grandma', name: 'Grumpy Grandma', team: 'good', tier: 2, category: 'protect',
    nightAction: false, oncePerGame: false, priority: 0, minPlayers: 8, maxPlayers: 16, weight: 8,
    short: 'If the Killer or Assassin targets her, she kills them back.',
    ability: 'Passive. If Grandma is attacked at night by the Killer or Assassin, the attacker dies instead (or in addition, if she is unprotected).',
    objective: 'Identify and eliminate every Evil player.',
    activates: 'Automatically, whenever she is attacked at night.',
    limitations: 'Only triggers against the Killer or Assassin, not against poison or other effects.',
    interactions: 'Works even if Grandma herself dies from the attack. Does not trigger from a roleblock or non-lethal effect.',
  },
  politician: {
    id: 'politician', name: 'Politician', team: 'good', tier: 2, category: 'social',
    nightAction: false, oncePerGame: false, priority: 0, minPlayers: 10, maxPlayers: 16, weight: 6,
    short: 'Their vote during the day counts twice.',
    ability: 'During the day, the Politician\'s vote counts as two votes instead of one.',
    objective: 'Identify and eliminate every Evil player.',
    activates: 'Every day vote, while alive.',
    limitations: 'Has no night action.',
    interactions: 'Applies before ties are checked; can single-handedly break a tie.',
  },
  gossip: {
    id: 'gossip', name: 'Gossip', team: 'good', tier: 3, category: 'info',
    nightAction: true, oncePerGame: false, priority: 84, minPlayers: 11, maxPlayers: 16, weight: 6,
    short: 'Learns whether two chosen players share the same team.',
    ability: 'Each night, choose two living players. Privately learn whether they belong to the same team or different teams (not which team).',
    objective: 'Identify and eliminate every Evil player.',
    activates: 'Every night, once alive.',
    limitations: 'Never reveals which team, only same or different.',
    interactions: 'Blocked by Bartender roleblock (result withheld).',
  },
  medium: {
    id: 'medium', name: 'Medium', team: 'good', tier: 3, category: 'info',
    nightAction: true, oncePerGame: true, priority: 86, minPlayers: 11, maxPlayers: 16, weight: 5,
    short: 'Once per game, privately asks one dead player a yes/no question.',
    ability: 'Once per game, at night, choose one dead player. The narrator privately relays one yes/no fact about that dead player\'s role or actions to the Medium.',
    objective: 'Identify and eliminate every Evil player.',
    activates: 'Any single night of the Medium\'s choosing, once alive.',
    limitations: 'Can only be used once per game and only targets dead players.',
    interactions: 'Not blockable by roleblocks once the ability begins resolving, since it targets no living player.',
  },
  cupid: {
    id: 'cupid', name: 'Cupid', team: 'neutral', tier: 2, category: 'chaos',
    nightAction: true, oncePerGame: true, priority: 5, minPlayers: 8, maxPlayers: 16, weight: 7,
    short: 'On the first night, links two players as Lovers.',
    ability: 'On Night 1 only, choose two living players to become Lovers. If either Lover dies for any reason, the other dies of heartbreak immediately after.',
    objective: 'Survive, and see at least one Lover survive to the end. Lovers who are on opposing teams instead win together if only the two of them remain.',
    activates: 'Night 1 only.',
    limitations: 'Cannot be used again after Night 1. Cupid may choose themself as one Lover.',
    interactions: 'Heartbreak deaths can chain into further effects (e.g. a heartbroken Grandma still triggers her revenge).',
  },
  clown: {
    id: 'clown', name: 'Clown', team: 'neutral', tier: 2, category: 'chaos',
    nightAction: false, oncePerGame: false, priority: 0, minPlayers: 9, maxPlayers: 16, weight: 8,
    short: 'Wins immediately if voted out and executed by the village.',
    ability: 'Passive. If the Clown is executed by a day vote, the Clown wins the game instantly, regardless of what happens afterward.',
    objective: 'Get yourself executed by the village vote.',
    activates: 'Automatically, at the moment of execution.',
    limitations: 'Does not win from a night death, only from a day execution.',
    interactions: 'A Clown execution still ends the day normally for other win checks, but the Clown\'s own win is locked in immediately.',
  },
};

export const ALL_ROLE_IDS = Object.keys(ROLES) as RoleId[];
